version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10.0
    steps:
      - checkout  
      - run:
          name: Install librarys
          command: pip install -r Requirements.txt  
      - run:
          name: Run data-analysis 
          command: python data-analysis.py  
      - run:
          name: Run tests suite
          command: pytest  

workflows:
  version: 2
  test-and-build:
    jobs:
      - test